//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonPartners.WordGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxonPartners.WordGenerator.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string canMakePayments_False {
            get {
                return ResourceManager.GetString("canMakePayments_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) We may hire other companies to perform certain business related functions such as processing payments on our behalf. Our payment processing partner may request that you provide certain Personal Data (e.g., a valid government issued ID, your legal name, address, and date of birth, banking credentials) for the purpose of making payment through its financial institutions and complying with any applicable laws and regulations. They may also communicate directly with you regarding any issues as to a payment.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string canMakePayments_True {
            get {
                return ResourceManager.GetString("canMakePayments_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Data storage and security and cross-border transfer 
        ///1) We will use all reasonable measures to protect your Personal Data from unauthorized access, alteration, disclosure or removal. The Service is equipped with the means of security and protection of your Personal Data.
        ///2) Immediate access to your Personal Data is allowed only to us and persons authorized by us and involved in the maintenance of the Service. Such persons will strictly keep confidentiality of and prevent unauthorized third-party access [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///2. Data collection
        ///1) We do not collect your Personal Data when you provide us such data via the contact form on our Service..
        /// </summary>
        internal static string hasContactForm_False {
            get {
                return ResourceManager.GetString("hasContactForm_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///2. Data collection
        ///1) We collect your Personal Data when you provide us such data via the contact form on our Service..
        /// </summary>
        internal static string hasContactForm_True {
            get {
                return ResourceManager.GetString("hasContactForm_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) We do not use cookies or other similar technologies to collect your Personal Data..
        /// </summary>
        internal static string hasCookies_False {
            get {
                return ResourceManager.GetString("hasCookies_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) We may collect some Personal Data automatically (your IP address, browser type and version, information about your visit including the URL clickstream to, through and from our Service, web pages you viewed or searched for, length of visits to certain web pages, web page interaction), through the use of tracking technologies including cookies due to our Privacy Policy..
        /// </summary>
        internal static string hasCookies_True {
            get {
                return ResourceManager.GetString("hasCookies_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) By using the *PROJECT* (also, the Service), you accept this Privacy Policy and consent to the collection, storage, use, and disclosure of your Personal Data in accordance with this Privacy Policy and applicable legislation. You may withdraw your consent and require removal of your Personal Data by contacting us using the information in this paper..
        /// </summary>
        internal static string hasUserRegistration_False {
            get {
                return ResourceManager.GetString("hasUserRegistration_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) By registering on the *PROJECT* (also, the Service), you accept this Privacy Policy and consent to the collection, storage, use, and disclosure of your Personal Data in accordance with this Privacy Policy and applicable legislation. You may withdraw your consent and require removal of your Personal Data by contacting us using the information in this paper..
        /// </summary>
        internal static string hasUserRegistration_True {
            get {
                return ResourceManager.GetString("hasUserRegistration_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///5. Third parties’ services
        ///1) We do not sell, provide on lease, or share any Personal Data of the Users to third parties.
        ///2) When we use third-party vendors to perform certain services on behalf of us, such as hosting the site or application, analytical or other services, such third-party vendors may collect or have access to information about you (for example, automatically collected information through tracking technologies). Please recognize that we and/or our vendors may store this information and s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isExternalLinks_False {
            get {
                return ResourceManager.GetString("isExternalLinks_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///5. Third parties’ services
        ///1) We do not sell, provide on lease, or share any Personal Data of the Users to third parties.
        ///2) Our Service may contain links to and from third parties’ websites, apps or other services (including social media). If you follow a link to any of them, please note that those websites have their own privacy practices. We shall not be liable for the respective policies and any collection, use or disclosure of your Personal Data in accordance thereto. Please check the third parties [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isExternalLinks_True {
            get {
                return ResourceManager.GetString("isExternalLinks_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Introductory
        ///1) Please read this Privacy Policy carefully. This Privacy Policy constitutes the integral part of the agreement between you (also, the &apos;&apos;User&apos;&apos;) and the *ORGANIZATION* (also, the &apos;&apos;Company&apos;&apos;), address: *ADRESS*.
        ///2) This Privacy Policy describes the Company&apos;s privacy practices with regard to your Personal Data. Personal Data includes any data about you that specifically identifies you as an individual and information about your activities, such as information about your use of our Service, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isToUExist_False {
            get {
                return ResourceManager.GetString("isToUExist_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Introductory
        ///1) Please read this Privacy Policy carefully. This Privacy Policy constitutes the integral part of the agreement between you (also, the &apos;&apos;User&apos;&apos;) and the *ORGANIZATION* (also, the &apos;&apos;Company&apos;&apos;), address: *ADRESS*. This Privacy Policy is also the essential part of Terms of Use, that can be found here: *LINK.TERMSOFUSE*.
        ///2) This Privacy Policy describes the Company&apos;s privacy practices with regard to your Personal Data. Personal Data includes any data about you that specifically identifies you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isToUExist_True {
            get {
                return ResourceManager.GetString("isToUExist_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///3. Use
        ///We may use your Personal Data for the following purposes:
        ///– Proper provision of our services;
        ///– Registration;
        ///– Processing of your inquiries and operations as to our Service;
        ///– Analyzing and understanding our audience for the purposes of improving the Service;
        ///– Preventing, detecting and investigating potentially prohibited or illegal activities, including fraud;
        ///– Investigate and/or enforce violations of our Terms of Use and/or this Privacy Policy, or to protect our interests in our operati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sendMarketingEmails_False {
            get {
                return ResourceManager.GetString("sendMarketingEmails_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///3. Use
        ///We may use your Personal Data for the following purposes:
        ///– Proper provision of our services;
        ///– Registration;
        ///– Processing of your inquiries and operations as to our Service;
        ///– Analyzing and understanding our audience for the purposes of improving the Service;
        ///– Preventing, detecting and investigating potentially prohibited or illegal activities, including fraud;
        ///– Investigate and/or enforce violations of our Terms of Use and/or this Privacy Policy, or to protect our interests in our operati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sendMarketingEmails_True {
            get {
                return ResourceManager.GetString("sendMarketingEmails_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///4. Disclosure
        ///1) We will not disclose Personal Data to the third parties, unless otherwise set fort by the applicable laws.
        ///We do not share Personal Data with companies, organizations and individuals outside of the Company otherwise than:
        ///a) with your consent: we will share Personal Data with companies, organizations or individuals outside of the Company when we have your consent to do so. We require opt-in consent for the sharing of any sensitive Personal Data.
        ///b) for external processing: we provide  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shareDataTo3dParties_False {
            get {
                return ResourceManager.GetString("shareDataTo3dParties_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///4. Disclosure
        ///1) We may disclose some information with certain third parties.
        ///We do not share certain information with companies, organizations and individuals outside of the Company unless one of the following circumstances applies:
        ///a) We will share your Personal Data with companies, organizations or individuals outside of the Company if we have a good-faith belief that access, use, preservation or disclosure of the Personal Data is reasonably necessary to:
        ///– meet any applicable law, regulation, lega [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shareDataTo3dParties_True {
            get {
                return ResourceManager.GetString("shareDataTo3dParties_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string useCameras_False {
            get {
                return ResourceManager.GetString("useCameras_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) We may also ask you to provide us access to your camera/microphone to enable some functions of our Service. We will collect and use or disclose such information solely for the purposes and under the provisions of Sections 3 and 4 hereof..
        /// </summary>
        internal static string useCameras_True {
            get {
                return ResourceManager.GetString("useCameras_True", resourceCulture);
            }
        }
    }
}
